const mockFixtures = {
    missingHomeTeam: {
        awayTeam: 'Pandora FC',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-13T12:30',
        referee: 'Kunle Amhed',
        city: 'Kano',
        country: 'Nigeria',
    },
    missingAwayTeam: {
        homeTeam: 'Kano Pillars',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-13T12:30',
        referee: 'Kunle Amhed',
        city: 'Kano',
        country: 'Nigeria',
    },
    missingStadium: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Pandora FC',
        happeningOn: '2019-12-13T12:30',
        referee: 'Kunle Amhed',
        city: 'Kano',
        country: 'Nigeria',
    },
    missingHappeningOn: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Pandora FC',
        stadium: 'Kano Pillars Stadium',
        referee: 'Kunle Amhed',
        city: 'Kano',
        country: 'Nigeria',
    },
    missingReferee: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Pandora FC',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-13T12:30',
        city: 'Kano',
        country: 'Nigeria',
    },
    missingCity: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Pandora FC',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-13T12:30',
        referee: 'Kunle Amhed',
        country: 'Nigeria',
    },
    missingCountry: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Pandora FC',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-13T12:30',
        referee: 'Kunle Amhed',
        city: 'Kano',
    },
    invalidDateTime: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Pandora FC',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-1312:30',
        referee: 'Kunle Amhed',
        city: 'Kano',
        country: 'Nigeria',
    },
    sameTeams: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Kano Pillars',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-13T12:30',
        referee: 'Kunle Amhed',
        city: 'Kano',
        country: 'Nigeria',
    },
    firstFixture: {
        homeTeam: 'Kano Pillars',
        awayTeam: 'Pandora FC',
        stadium: 'Kano Pillars Stadium',
        happeningOn: '2019-12-13T12:30',
        referee: 'Kunle Amhed',
        city: 'Kano',
        country: 'Nigeria',
    },
    secondFixture: {
        homeTeam: 'Kiwi FC',
        awayTeam: 'Sharks',
        stadium: 'Kiwi Arena',
        happeningOn: '2020-12-14T12:30',
        referee: 'Sambo',
        city: 'Kiwi City',
        country: 'Kiwi Land',
    },
    thirdFixture: {
        homeTeam: 'Pandora FC',
        awayTeam: 'Kano Pillars',
        stadium: 'Pandora Stadium',
        happeningOn: '2021-01-13T12:30',
        referee: 'Segun Amhed',
        city: 'Abuja',
        country: 'Nigeria',
    },
    fixtureToEdit: {
        homeTeam: 'Panda FC',
        awayTeam: 'Kano Pillars',
        stadium: 'Panda Stadium',
        happeningOn: '2021-01-13T12:30',
        referee: 'Segun Amhed',
        city: 'Abuja',
        country: 'Nigeria',
    },
    finalFixture: {
        homeTeam: 'Owls FC',
        awayTeam: 'Crows FC',
        stadium: 'Owl City',
        happeningOn: '2020-02-04T12:30',
        referee: 'Robinson',
        city: 'Abuja',
        country: 'Nigeria', 
    }
};

export default mockFixtures;